title: "Sharmila Eday — AI/ML Portfolio"
name: "Sharmila Eday"
description: "Master of Science in Artificial Intelligence @UNT — projects, blog, and contact."
url: "https://sharmilaeday.github.io"  # don't add a trailing slash
baseurl: ""  # leave empty for user site

# Use Minimal Mistakes theme
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default" # options: air, aqua, contrast, dark, dirt, neon, mint, sunrise

markdown: kramdown
paginate: 5

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

author:
  avatar: "/assets/img/Sharmila.JPG"
  name: "Sharmila Eday"
  bio: "MS in AI @ UNT · Focus: NLP, GenAI, and MLOps · Open to AI/ML roles"
  location: "Dallas–Fort Worth, TX"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:sharmilaeday@gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/sharmilaeday/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/SharmilaEday"
    - label: "Resume (PDF)"
      icon: "fas fa-fw fa-file-pdf"
      url: "/assets/resume.pdf"

# Collections for projects
collections:
  projects:
    output: true
    permalink: /projects/:name/

# Defaults for layouts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author_profile: true
      read_time: true
      share: true
      comments: false
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "single"
      author_profile: true
      share: true

# SEO/Open Graph
logo: "/assets/img/Sharmila.JPG"
github_username: "SharmilaEday"
og_image: "/assets/img/og-image.png"

